# Numpy

### Assignments

##### Problem Statement 1

Write a function so that the columns of the output matrix are powers of the input vector

The order of the powers is determined by the increasing boolean argument. Specifically, when increasingis False, the ith output column is the input vector raised element-wise to the power of (N-i-1). 

Hint: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 

In [3]:
import numpy as np

In [21]:
# x - 1-D input array. 
x = np.array([1,2,3,5])

In [22]:
# N - Number of columns in the output if 'N' is not specified a square array is returned (N=len(x))
N = 3

In [23]:
np.vander(x,N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [24]:
np.column_stack([x**(N-i-1) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [25]:
# increasing - Order of the powers of the columns. If True, the powers increase from left to right,
# if False (the default) they are reversed. 
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

The determinant of square Vandermonde matrix is the product of the differences between the values of the input vector:

In [26]:
np.linalg.det(np.vander(x))

48.00000000000003

In [27]:
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48

##### Problem Statement 2

Given a sequence of 'n' values x1, x2, ... Xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has (n-k+1) elements as shown below.

The moving averages with k=4 of a ten-values sequence (n=10) is shown below:


i = 1 2 3 4 5 6 7 8 9 10


input = 10 20 30 40 50 60 70 80 90 100

Y1  25 = (10+20+30+40)/4

Y2  35 = (20+30+40+50)/4

Y3  45 = (30+40+50+60)/4

Y4  55 = (40+50+60+70)/4

Y5  65 = (50+60+70+80)/4

Y6  75 = (60+70+80+90)/4

Y7  85 = (70+80+90+100)/4


Thus the moving average sequence has (n-k+1) = 10-4+1 = 7 Values. 

Question: Write a function to find moving average in an array over a window: 
    Test it over[3,5,7,2,8,10,11,65,72,81,99,100,150] and window of 3. 

In [1]:
import numpy as np

In [2]:
def movingAverage(l, win):
    print("Length of the sequence: {}".format(len(l)))
    for i in range((len(l)-win+1)):#(n-k+1)
        sum = 0        
        for j in range(win):
            sum += l[j+i]
        print("Y{} = {}".format(i,(sum/win)))

#Sequence.        
x=[3,5,7,2,8,10,11,65,72,81,99,100,150]

# K - Window size 3. 
movingAverage(x, 3)

Length of the sequence: 13
Y0 = 5.0
Y1 = 4.666666666666667
Y2 = 5.666666666666667
Y3 = 6.666666666666667
Y4 = 9.666666666666666
Y5 = 28.666666666666668
Y6 = 49.333333333333336
Y7 = 72.66666666666667
Y8 = 84.0
Y9 = 93.33333333333333
Y10 = 116.33333333333333
